services:
  node1:
    build:
      context: go_service
    environment:
      - PORT=9090
    ports:
      - "9090:9090"
  node2:
    build:
      context: go_service
    environment:
      - PORT=9091
    ports:
      - "9091:9091"
  http-service-discovery:
    build:
      context: http_service_discovery
    environment:
      - PORT=9000
    ports:
      - "9000:9000"